<?php

return [
    'temporary_file_upload' => [
        'disk' => 'cloudinary',
        'rules' => null,
        'directory' => null,
        'middleware' => null,
        'preview_mimes' => [
            'png',
            'jpg',
            'jpeg',
            'gif',
            'bmp',
            'svg',
            'webp',
            'mp4',
            'mov',
            'avi',
            'wmv',
            'mp3',
            'wav',
            'ogg',
            'pdf',
            'txt',
            'doc',
            'docx',
            'xls',
            'xlsx',
            'csv',
            'zip',
            'rar',
            '7z',
            'tar',
            'gz',
        ],
        'max_upload_time' => 5,
    ],
];